language: python

# 2.7, 3.5, and 3.6 covers 99% of all python users
python:
    - 2.7
    - 3.5
    - 3.6

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

script:
  - pytest --cov=autodeploy --cov-report term-missing
